### ISSUE TITLE
Too many arguments for `highlight link` using Solarized colorscheme

### ISSUE THREAD

**Issue by nickwynja** [oblitum/goyo.vim#1] opened 2018-11-26 14:37 UTC
Hi @oblitum,

As discussed in https://github.com/junegunn/goyo.vim/issues/156, I'm getting a `Too many arguments` error. I'm using neovim `v0.3.1` and `colorscheme solarized`.

The error I'm receiving is as follows:

```
Error detected while processing function goyo#execute[20]..<SNR>143_goyo_off[59]..<SNR>143_restore:
line   10:
E413: Too many arguments: ":highlight link SignColumn ctermfg=12 ctermbg=242 guifg=Cyan guibg=Grey LineNr"
```

Additional relevant configurations I have are:

```vim
set signcolumn=yes
set number
```

**Comment by oblitum** [comment] 2018-11-26 14:38
OK thanks!, I'll check.

**Comment by oblitum** [comment] 2018-11-26 14:45
I'm also on 0.3.1 and I'm not getting the error switching back and forth through goyo mode with that colorscheme and settings... any additional colorscheme patches you apply in `.vimc`, is it stock solarized?

**Comment by oblitum** [comment] 2018-11-26 14:56
By the way, I'm testing on top of the patch that keep the original groups, I've noticed that it doesn't hide `~`, but in my last commit I do hide, fyi, the additional group you can add to the original set to hide those tildes is `EndOfBuffer`.

**Comment by oblitum** [comment] 2018-11-26 14:58
> By the way, I'm testing on top of the patch that keep the original groups, I've noticed that it doesn't hide `~`, but in my last commit I do hide, fyi, the additional group you can add to the original set to hide those tildes is `EndOfBuffer`.

Ops, looks like adding it doesn't make any diff for solarized.

**Comment by nickwynja** [comment] 2018-11-26 14:59
I'm installing using `Plug 'altercation/vim-colors-solarized'`. The only other solarized setting I have is `let g:solarized_italic = 1`.

I'm really not sure where the `link` is even coming from since it's not defined in the source:

https://github.com/altercation/vim-colors-solarized/blob/528a59f26d12278698bb946f8fb82a63711eec21/colors/solarized.vim#L657

When I run `:hi SignColumn`, I get:

```
SignColumn     xxx ctermfg=11 ctermbg=248 guifg=DarkBlue guibg=Grey
                   links to LineNr
```

I had been previously using a patch similar to your https://github.com/oblitum/dotfiles/commit/4d4169ab55501304c69ca76c74dcecd5bb243337#diff-4e12c6a37ff2cbb2c93d1b33324a6051, including, I believe, running a `highlight link` command myself to discover which UI artifacts I could remove manually. I'm thinking this could have been cached somewhere? Seems like `hi clear SignColumn` doesn't do anything and the `link` returns on restarting vim.

**Comment by oblitum** [comment] 2018-11-26 15:06
Ok, is that `:hi SignColumn` output prior to entering Goyo, because the backup/recover process may generate that if it's broken. I also try to avoid mess calling `hi! clear` in it. I need to differentiate whether that bad setting is coming from it or not. Try `:hi SignColumn` with your settings once you start NeoVim, if you didn't already.

**Comment by oblitum** [comment] 2018-11-26 15:08
Also, you shouldn't need that old patch anymore, you can patch other stuff, but that patch was doing manually what the fork is doing automatically now for any colorscheme.

**Comment by nickwynja** [comment] 2018-11-26 15:11
I found the source of the `link`. I use `vim-gitgutter` and it's generating the link:

https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter/highlight.vim#L35-L41

**Comment by oblitum** [comment] 2018-11-26 15:15
Well, that solarized is completely different from stock, my comments on tildes don't apply just fyi, there's no ~ in it with Goyo. Still, I'm also using gitgutter, no issues... if you care I'll produce a debugging version in that function because even though the colors may be bad from elsewhere, I want it to work regardless.

**Comment by oblitum** [comment] 2018-11-26 15:18
Hmm, I use gitgutter but I've left that setting off specifically, will check with it on.

**Comment by nickwynja** [comment] 2018-11-26 15:21
This is what I use, for reference:

```
" Git-gutter
let g:gitgutter_sign_added = '●'
let g:gitgutter_sign_modified = '●'
let g:gitgutter_sign_removed = '●'
let g:gitgutter_sign_modified_removed = '●'
```

**Comment by oblitum** [comment] 2018-11-26 15:21
Indeed reproduced! I'll fix to cope with that. Also, I'm not sure, but maybe GitGutter should have been calling a `hi! clear` prior to calling `hi! link`.

**Comment by oblitum** [comment] 2018-11-26 18:11
Should be fixed at e6def71, please confirm. You can also use my master now, I've put my personal set of groups to tranquilize in a specific branch. Though on master there's no `GoyoEnter`/`GoyoLeave` anymore, if you want to use the User autocmd hooks, use the `GoyoEnterPre`/`GoyoEnterPost`/`GoyoLeaveEnter`/`GoyoLeavePost`.

I've implemented in a way that recovering will leave groups like GitGutter leaves them, with the extra `links` overriding the original colors, not trying to removing anything from original, even if it's a weird setting.

**Closed by oblitum** 2018-11-26 18:11 UTC

**Comment by oblitum** [comment] 2018-11-26 18:18
`reset --hard` or clone it over.

**Comment by nickwynja** [comment] 2018-11-26 18:23
Confirmed it's working! Thank you so much.

If you wouldn't mind explaining, what are you using the more specific enter/leave lifecycle hooks for?

**Comment by oblitum** [comment] 2018-11-26 18:41
@nickwynja when I execute `nvim -c Goyo file`, (neo)vim calls Goyo plugin-related stuff too early, before stuff from my `.vimrc` are setu. I'm refactoring my `.vimrc` and locally it's completely different from my current dotfiles in master, so you can't check what not, but for example, I have some VimEnter autocmds in my `.vimrc` that call a function, which I expect to execute prior to entering Goyo, that happens in normal situations, but not when I start (neo)vim with Goyo already on. Hence I've made that more precise, and on my GoyoEnterPre, I check if that function had been executed already, if not, I execute it.

**Comment by oblitum** [comment] 2018-11-26 19:32
OK. The old User autocmd hooks are the current "Post" hooks in master. You may run into such issue if you start (neo)vim already inside Goyo, I do that for [writing posts](http://nosubstance.me/post/a-great-toolset-for-static-blogging/), [emails](http://nosubstance.me/post/mutt-secret-sauce/), etc, because `vim -c Goyo` is executed by NeoMutt, etc, not myself :) If you start to adopt that, **and** have autocmds in your `.vimrc` that need to run before Goyo, then you may face it, otherwise not.

**Comment by nickwynja** [comment] 2018-11-26 19:39
Interesting looking posts, looking forward to giving them a read. I do in fact have a similar `zsh` alias:
```
alias write="vim -c 'set ft=markdown | startinsert | Minimal'"
```
where `Minimal()` is a wrapper for triggering Goyo. I only have few basic `autocmd`s right now but will keep an eye out for issues there.
